name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Python Black
        uses: psf/black@stable
        continue-on-error: true
        with: 
          options: "--check --diff"
          src: "."
      - name: Run Bandit Scanner
        uses: reactive-firewall/python-bandit-scan@v2.3
        with:
          path: "."
          level: high
          confindence: high
          exit_zero: true
      
  
