name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Python Black
        uses: psf/black@stable
        with: 
          options: "--check --diff"
          src: "."
  
